name: "excel_summary"

services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    volumes:
      - ./src:/app/src
    ports:
      - "$HOST_PORT:8000"
    working_dir: "/app"
    env_file:
      - .env
    entrypoint: ./scripts/start.sh
  postgres:
    image: "postgres:alpine"
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql/data
